inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - standard

inherit_gem:
  standard: config/base.yml

inherit_from:
  - .rubocop/custom.yml

# Where are all the new cops? Check in .rubocop/custom.yml
