host: "localhost:3000"
folio:
  url: "https://okapi-dev.example.com"
  username: "app_libsys"
  password: "supersecret" # vault kv get puppet/application/folio/app_libsys_password
  tenant_id: "example_tenant"
